In [1]:
from statsbombpy import sb

In [ ]:

competiciones = sb.competitions() # Aquí obtienes una lista de todas las competiciones disponibles en la base de datos de StatsBomb. Cada competición tiene un "competition_id" y un "season_id" que son esenciales para acceder a los datos específicos de esa liga y temporada.

competiciones.head() # Esto te muestra las primeras filas de la tabla de competiciones, donde podrás identificar fácilmente los "competition_id" y "season_id" para las ligas que te interesan.

# BUSCAR: competition_id y season_id:, stos dos números son las "llaves" de tu ecosistema. Los necesitarás para extraer los partidos de esa liga específica.
# BUSCAR: competition_name: Aquí verás nombres como "World Cup", "La Liga", "Champions League", etc.

# Para la Premier League, el competition_id es 11 y el season_id es 43 (2022/2023).
# Para la Liga, el competition_id es 12 y el season_id es 43 (2022/2023).
# Para la Bundesliga, el competition_id es 1 y el season_id es 43 (2022/2023).
# Para la Serie A, el competition_id es 2 y el season_id es 43 (2022/2023).
# Para la Ligue 1, el competition_id es 3 y el season_id es 43 (2022/2023).
# Para la Eredivisie, el competition_id es 4 y el season_id es 43 (2022/2023).
# Para la Liga Profesional Argentina, el competition_id es 5 y el season_id es 43 (2022/2023).
# Para la Major League Soccer, el competition_id es 6 y el season_id es 43 (2022/2023).

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,NaN,NaN,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,NaN,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882

In [10]:
# 1. Traemos todas las competiciones
competiciones = sb.competitions()

# 2. Seleccionamos las columnas clave
info_ligas = competiciones[['competition_id', 'season_id', 'competition_name', 'season_name', 'competition_gender']]

# 3. ORDENAMOS: Ponemos lo más nuevo arriba (ascending=False)
# Ordenamos primero por nombre de liga y luego por temporada
info_ligas_ordenadas = info_ligas.sort_values(by=[ 'season_name', 'competition_gender' ], ascending=False)

# 4. Mostramos las primeras 20 ahora que están ordenadas
info_ligas_ordenadas.head(20)

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,competition_name,season_name,competition_gender
71,53,315,UEFA Women's Euro,2025,female
21,223,282,Copa America,2024,male
68,55,282,UEFA Euro,2024,male
0,9,281,1. Bundesliga,2023/2024,male
2,1267,107,African Cup of Nations,2023,male
61,44,107,Major League Soccer,2023,male
73,72,107,Women's World Cup,2023,female
58,7,235,Ligue 1,2022/2023,male
29,43,106,FIFA World Cup,2022,male
72,53,106,UEFA Women's Euro,2022,female
37,1238,108,Indian Super league,2021/2022,male
59,7,108,Ligue 1,2021/2022,male
38,11,90,La Liga,2020/2021,male
25,37,90,FA Women's Super League,2020/2021,female
69,55,43,UEFA Euro,2020,male
39,11,42,La Liga,2019/2020,male
26,37,42,FA Women's Super League,2019/2020,female
74,72,30,Women's World Cup,2019,female
3,16,4,Champions League,2018/2019,male
40,11,4,La Liga,2018/2019,male

In [3]:
sb.matches(competition_id=2, season_id=27)


# Para la Premier League, el competition_id es 11 y el season_id es 43 (2022/2023).
# Para la Liga, el competition_id es 12 y el season_id es 43 (2022/2023).
# Para la Bundesliga, el competition_id es 1 y el season_id es 43 (2022/2023).
# Para la Serie A, el competition_id es 2 y el season_id es 43 (2022/2023).
# Para la Ligue 1, el competition_id es 3 y el season_id es 43 (2022/2023).
# Para la Eredivisie, el competition_id es 4 y el season_id es 43 (2022/2023).
# Para la Liga Profesional Argentina, el competition_id es 5 y el season_id es 43 (2022/2023).
# Para la Major League Soccer, el competition_id es 6 y el season_id es 43 (2022/2023).

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3754058,2016-01-02,16:00:00.000,England - Premier League,2015/2016,Leicester City,AFC Bournemouth,0,0,available,...,2021-06-12T16:17:31.694,20,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Eddie Howe,1.1.0,2,2
1,3754245,2015-10-17,16:00:00.000,England - Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,available,...,2021-06-13T16:17:31.694,9,Regular Season,The Hawthorns,Martin Atkinson,Tony Pulis,Sam Allardyce,1.1.0,2,2
2,3754136,2015-12-19,18:30:00.000,England - Premier League,2015/2016,Newcastle United,Aston Villa,1,1,available,...,2021-06-13T16:17:31.694,17,Regular Season,St. James'' Park,Martin Atkinson,Steve McClaren,Rémi Garde,1.1.0,2,2
3,3754037,2016-04-30,16:00:00.000,England - Premier League,2015/2016,Everton,AFC Bournemouth,2,1,available,...,2021-06-12T16:17:31.694,36,Regular Season,Goodison Park,Neil Swarbrick,Roberto Martínez Montoliú,Eddie Howe,1.1.0,2,2
4,3754039,2016-02-13,16:00:00.000,England - Premier League,2015/2016,Crystal Palace,Watford,1,2,available,...,2021-06-12T16:17:31.694,26,Regular Season,Selhurst Park,Robert Madley,Alan Pardew,Enrique Sánchez Flores,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,3754020,2015-08-17,21:00:00.000,England - Premier League,2015/2016,Liverpool,AFC Bournemouth,1,0,available,...,2021-06-13T16:17:31.694,2,Regular Season,Anfield,Craig Pawson,Brendan Rodgers,Eddie Howe,1.1.0,2,2
376,3754267,2015-08-15,16:00:00.000,England - Premier League,2015/2016,Watford,West Bromwich Albion,0,0,available,...,2021-06-13T16:17:31.694,2,Regular Season,Vicarage Road,Paul Tierney,Enrique Sánchez Flores,Tony Pulis,1.1.0,2,2
377,3754141,2015-08-09,14:30:00.000,England - Premier League,2015/2016,Arsenal,West Ham United,0,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Emirates Stadium,Martin Atkinson,Arsène Wenger,Slaven Bilić,1.1.0,2,2
378,3754128,2015-08-08,16:00:00.000,England - Premier League,2015/2016,AFC Bournemouth,Aston Villa,0,1,available,...,2021-06-13T16:17:31.694,1,Regular Season,Vitality Stadium,Mark Clattenburg,Eddie Howe,Tim Sherwood,1.1.0,2,2
379,3754078,2015-08-08,18:30:00.000,England - Premier League,2015/2016,Chelsea,Swansea City,2,2,available,...,2021-06-13T16:17:31.694,1,Regular Season,Stamford Bridge,Michael Oliver,José Mario Felix dos Santos Mourinho,Garry Monk,1.1.0,2,2

In [4]:
# Asignamos los partidos a una variable
partidos = sb.matches(competition_id=2, season_id=27)

# Ahora mostramos los primeros 5
partidos.head()

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3754058,2016-01-02,16:00:00.000,England - Premier League,2015/2016,Leicester City,AFC Bournemouth,0,0,available,...,2021-06-12T16:17:31.694,20,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Eddie Howe,1.1.0,2,2
1,3754245,2015-10-17,16:00:00.000,England - Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,available,...,2021-06-13T16:17:31.694,9,Regular Season,The Hawthorns,Martin Atkinson,Tony Pulis,Sam Allardyce,1.1.0,2,2
2,3754136,2015-12-19,18:30:00.000,England - Premier League,2015/2016,Newcastle United,Aston Villa,1,1,available,...,2021-06-13T16:17:31.694,17,Regular Season,St. James'' Park,Martin Atkinson,Steve McClaren,Rémi Garde,1.1.0,2,2
3,3754037,2016-04-30,16:00:00.000,England - Premier League,2015/2016,Everton,AFC Bournemouth,2,1,available,...,2021-06-12T16:17:31.694,36,Regular Season,Goodison Park,Neil Swarbrick,Roberto Martínez Montoliú,Eddie Howe,1.1.0,2,2
4,3754039,2016-02-13,16:00:00.000,England - Premier League,2015/2016,Crystal Palace,Watford,1,2,available,...,2021-06-12T16:17:31.694,26,Regular Season,Selhurst Park,Robert Madley,Alan Pardew,Enrique Sánchez Flores,1.1.0,2,2

In [10]:
sb.events(match_id=3754058, split=True, flatten_attrs=False).keys()

c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

dict_keys(['starting_xis', 'half_starts', 'passes', 'ball_receipts', 'carrys', 'pressures', 'dispossesseds', 'duels', 'shots', 'blocks', 'goal_keepers', 'ball_recoverys', 'miscontrols', 'clearances', 'dribbled_pasts', 'dribbles', 'interceptions', 'foul_committeds', 'foul_wons', 'half_ends', 'substitutions', 'injury_stoppages', 'tactical_shifts', 'shields'])

In [11]:
sb.events(match_id=3754058, split=True, flatten_attrs=False)['shots']

c:\Users\federab\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,position,location,duration,related_events,shot,match_id,possession_team_id,team_id,player_id,under_pressure
0,72596ffe-393e-4a75-82c6-5fb82ae36d4d,93,1,00:01:33.287,1,33,Shot,4,AFC Bournemouth,Regular Play,...,Left Midfield,"[107.1, 26.6]",0.271905,"[1b9c4015-67df-4597-a410-9b9f66d71fef, a6ca787...","{'statsbomb_xg': 0.02083787, 'end_location': [...",3754058,28,28,3463,NaN
1,b2bae775-5dd8-45bf-9b84-191c7849f707,224,1,00:04:23.399,4,23,Shot,9,AFC Bournemouth,Regular Play,...,Center Forward,"[113.7, 54.0]",0.236075,"[a351d3d5-b02f-4576-995f-fc435e5768d6, f38d30f...","{'statsbomb_xg': 0.034461774, 'end_location': ...",3754058,28,28,3346,NaN
2,7c4227e5-0759-4633-93ea-bbbe291bbd72,440,1,00:09:20.642,9,20,Shot,16,Leicester City,Regular Play,...,Right Midfield,"[115.7, 50.5]",0.770062,"[6a0bf226-4535-4738-b445-17f03ec3416b, eb9b259...","{'statsbomb_xg': 0.035480928, 'end_location': ...",3754058,22,22,3814,True
3,8e3a6f10-64e4-49bf-a157-16b15b552713,579,1,00:13:11.270,13,11,Shot,20,AFC Bournemouth,From Throw In,...,Center Forward,"[113.9, 38.6]",0.884091,[40d7f263-24e6-4b30-8bc7-9e3214bcc770],"{'statsbomb_xg': 0.38371146, 'end_location': [...",3754058,28,28,3346,NaN
4,3a5364b3-0b99-4271-a451-0a3033ad195d,1170,1,00:25:47.089,25,47,Shot,47,Leicester City,From Free Kick,...,Right Center Forward,"[96.7, 47.2]",0.826620,[bb2f23ab-e882-42d6-9b75-7feb47131c97],"{'statsbomb_xg': 0.036740057, 'end_location': ...",3754058,22,22,3671,NaN
5,1d66ec6b-17ea-418d-a390-b5b4ac0f8181,1177,1,00:25:49.025,25,49,Shot,47,Leicester City,From Free Kick,...,Left Center Forward,"[111.3, 38.7]",0.423901,[0a7eb203-368d-4ec5-b302-a25f6c945da1],"{'one_on_one': True, 'statsbomb_xg': 0.5754278...",3754058,22,22,10960,NaN
6,e766a3d8-8a5e-42d2-aea1-378af85d8c6b,1432,1,00:32:14.772,32,14,Shot,58,AFC Bournemouth,From Throw In,...,Left Midfield,"[112.6, 28.7]",0.481125,[f68e5686-23a9-4778-8dc2-c070f33412ef],"{'statsbomb_xg': 0.095997825, 'end_location': ...",3754058,28,28,3463,NaN
7,373e52d0-06f0-44bd-b62c-0a4fe528c6b4,1491,1,00:33:52.207,33,52,Shot,62,Leicester City,From Free Kick,...,Right Center Forward,"[112.1, 32.8]",1.891069,"[7d08bbf9-805b-4696-a288-568e24f255bc, af17ac2...","{'statsbomb_xg': 0.04725947, 'end_location': [...",3754058,22,22,3671,True
8,77d83d42-ad31-42c6-a606-415f6ac199b8,1602,1,00:36:57.340,36,57,Shot,68,AFC Bournemouth,From Free Kick,...,Right Center Midfield,"[108.4, 43.0]",0.718851,[b01462a7-4658-4f52-89c3-7dab1f95a661],"{'statsbomb_xg': 0.25644818, 'end_location': [...",3754058,28,28,3343,NaN
9,12ab3780-190a-477f-b832-8c612d0fd5b0,1616,1,00:37:43.021,37,43,Shot,69,Leicester City,From Goal Kick,...,Left Center Forward,"[114.2, 27.2]",1.143391,[9f934bea-3a38-4779-87e8-75ed86067cde],"{'one_on_one': True, 'statsbomb_xg': 0.1119732...",3754058,22,22,10960,NaN
10,75d2cbc8-05fb-4749-867b-2bf99fada8ff,2199,2,00:05:11.477,50,11,Shot,93,Leicester City,Regular Play,...,Left Center Forward,"[100.4, 33.3]",0.733531,"[79746062-9a24-4299-99f5-4bf3c08ddc1e, f6dee7e...","{'statsbomb_xg': 0.094897345, 'end_location': ...",3754058,22,22,10960,True
11,30c759a1-d45c-497c-b50e-c5573107122b,2205,2,00:05:55.805,50,55,Shot,94,Leicester City,From Corner,...,Right Center Back,"[117.3, 39.5]",0.568385,[249b6970-1e2c-4c15-8abd-5b9720230909],"{'statsbomb_xg': 0.64057934, 'end_location': [...",3754058,22,22,3813,NaN
12,f4be3b30-a789-4f02-8f16-ee9547c719cb,2524,2,00:13:11.928,58,11,Shot,109,Leicester City,Other,...,Right Midfield,"[108.4, 40.2]",0.395379,[8e52e556-3b67-4755-8d82-a1181f08140e],"{'statsbomb_xg': 0.7835, 'end_location': [118....",3754058,22,22,3814,NaN
13,7c27fea2-e387-423b-ae7b-cd60be0ec1e7,2668,2,00:18:04.761,63,4,Shot,118,AFC Bournemouth,From Throw In,...,Right Back,"[87.6, 45.6]",0.572722,"[80418e70-1444-4517-80cc-078dbc0f6bfa, f1800f3...","{'statsbomb_xg': 0.022849003, 'end_location': ...",3754058,28,28,6409,NaN
14,a5cc0f8a-6054-492f-afe3-c2574db1eda9,2674,2,00:18:09.179,63,9,Shot,118,AFC Bournemouth,From Throw In,...,Left Midfield,"[101.4, 29.4]",0.310609,"[0c0c5356-071e-48f6-8043-65aac6b79ba0, e3def97...","{'statsbomb_xg': 0.054560155, 'end_location': ...",3754058,28,28,3463,True
15,0eceba7b-61d4-4f2e-b1c9-6a73eee0162e,2682,2,00:18:48.141,63,48,Shot,119,AFC Bournemouth,From Corner,...,Right Back,"[88.5, 47.4]",0.319233,"[550d14a4-ba26-4e39-9561-431a5a4a861f, cae9a29...","{'statsbomb_xg': 0.01612113, 'end_location': [...",3754058,28,28,6409,NaN
16,e22f90a1-9494-4a0e-9a82-450d81070063,2713,2,00:20:43.400,65,43,Shot,122,Leicester City,From Corner,...,Left Defensive Midfield,"[97.0, 32.9]",0.991964,[8a61d53c-d198-41d4-84e8-bf6f0a973b38],"{'statsbomb_xg': 0.0250954, 'end_location': [1...",3754058,22,22,3961,NaN
17,a9326c0b-1e10-43f1-8d0d-de63ca8a6114,2772,2,00:24:09.928,69,9,Shot,129,Leicester City,From Throw In,...,Left Center Back,"[114.3, 30.0]",1.056613,[0f958577-df7c-4459-82d6-640ecab5e1d0],"{'statsbomb_xg': 0.05736443, 'end_location': [...",3754058,22,22,40123,NaN
18,24f7f6d4-bbb0-45da-8414-2cb58af7d8f4,2792,2,00:24:41.666,69,41,Shot,135,AFC Bournemouth,Regular Play,...,Left Back,"[98.5, 18.0]",1.599516,"[1b147a2a-6a6a-4532-8b51-ab8f85dfd5c9, c6585dd...","{'statsbomb_xg': 0.008613406, 'end_location': ...",3754058,28,28,3345,True
19,ca9b925c-13c5-4a4c-bcbb-d5c48ed89d91,2927,2,00:28:42.974,73,42,Shot,144,Leicester City,Regular Play,...,Left Midfield,"[103.7, 26.3]",1.747659,[493903c3-6de9-405a-816c-ce4f1a46bb8c],"{'statsbomb_xg': 0.039429333, 'end_location': ...",3754058,22,22,3810,NaN
20,7db239ff-9ff2-4e31-bb58-acb3a1cba52e,3003,2,00:30:36.443,75,36,Shot,149,Leicester City,From Throw In,...,Left Defensive Midfield,"[109.7, 43.2]",2.042701,[7572f278-b9f9-4f3b-a007-ca17f6b1d41d],"{'statsbomb_xg': 0.24525318, 'end_location': [...",3754058,22,22,3961,NaN
21,3ca8bc18-6083-4d5a-afc1-4dc20de42e43,3148,2,00:34:52.570,79,52,Shot,160,AFC Bournemouth,Regular Play,...,Right Center Midfield,"[103.0, 50.4]",0.237011,"[3e8b6494-79e8-4bf7-992d-d5194ffb4768, 74cf570...","{'statsbomb_xg': 0.042901754, 'end_location': ...",3754058,28,28,3343,True
22,ae5dfce5-95e6-47b1-b2e3-abc11d7d59f2,3241,2,00:37:59.235,82,59,Shot,167,Leicester City,From Corner,...,Left Center Forward,"[116.3, 53.9]",1.331448,"[07f680cc-e6cd-4797-bd19-fb19409a0516, a470dd0...","{'statsbomb_xg': 0.012095166, 'end_location': ...",3754058,22,22,10960,True
23,39ba03e1-5445-4735-a38e-c0b8330d9883,3293,2,00:40:00.384,85,0,Shot,171,Leicester City,Regular Play,...,Left Defensive Midfield,"[99.2, 23.6]",0.247703,"[1f04fc03-b5af-4f03-b42d-e0849b227515, 2c65be0...","{'statsbomb_xg': 0.023959583, 'end_location': ...",3754058,22,22,3961,True
24,4a791b58-400d-412b-89e9-7d6a8dc6d454,3302,2,00:40:09.307,85,9,Shot,171,Leicester City,Regular Play,...,Right Center Midfield,"[99.3, 37.5]",1.103284,[20781e33-7f92-4649-b4fd-9e87c5f58cec],"{'statsbomb_xg': 0.044721026, 'end_location': ...",3754058,22,22,3662,NaN
25,a2904741-25d0-4824-aa20-1aed74d26389,3400,2,00:43:18.687,88,18,Shot,180,Leicester City,From Free Kick,...,Right Midfield,"[91.1, 41.6]",0.378867,"[68c20cc2-16dc-4021-be10-5db533c39969, 6d6170e...","{'statsbomb_xg': 0.028252145, 'end_location': ...",3754058,22,22,3814,NaN
26,0deef0c6-856b-469c-bfaa-15264d794cd2,3410,2,00:43:44.492,88,44,Shot,181,Leicester City,From Corner,...,Left Defensive Midfield,"[96.0, 26.8]",1.237790,[af616b14-2ce3-4f25-b1e7-e910a2d134df],"{'statsbomb_xg': 0.020842131, 'end_location': ...",3754058,22,22,3961,NaN

In [16]:
from mplsoccer import Sbopen

parser = Sbopen()

In [18]:
len(parser.event(3754141))

4

In [19]:
df1, df2, df3, df4 = parser.event(3754141)

In [24]:
df4

,jersey_number,match_id,id,player_id,player_name,position_id,position_name,event_tactics_id
0,33,3754141,cc35d86a-b198-4275-9599-f65068240029,3461,Petr Čech,1,Goalkeeper,1
1,2,3754141,cc35d86a-b198-4275-9599-f65068240029,4428,Mathieu Debuchy,2,Right Back,2
2,4,3754141,cc35d86a-b198-4275-9599-f65068240029,3475,Per Mertesacker,3,Right Center Back,3
3,6,3754141,cc35d86a-b198-4275-9599-f65068240029,3394,Laurent Koscielny,5,Left Center Back,4
4,18,3754141,cc35d86a-b198-4275-9599-f65068240029,3498,Ignacio Monreal Eraso,6,Left Back,5
5,16,3754141,cc35d86a-b198-4275-9599-f65068240029,3517,Aaron Ramsey,9,Right Defensive Midfield,6
6,34,3754141,cc35d86a-b198-4275-9599-f65068240029,3437,Francis Joseph Coquelin,11,Left Defensive Midfield,7
7,15,3754141,cc35d86a-b198-4275-9599-f65068240029,3525,Alex Oxlade-Chamberlain,17,Right Wing,8
8,11,3754141,cc35d86a-b198-4275-9599-f65068240029,3496,Mesut Özil,19,Center Attacking Midfield,9
9,19,3754141,cc35d86a-b198-4275-9599-f65068240029,11386,Santiago Cazorla González,21,Left Wing,10
10,12,3754141,cc35d86a-b198-4275-9599-f65068240029,3604,Olivier Giroud,23,Center Forward,11
11,13,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3623,Adrián San Miguel del Castillo,1,Goalkeeper,1
12,5,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3316,James Tomkins,2,Right Back,2
13,2,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,4280,Winston Reid,3,Right Center Back,3
14,21,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3843,Angelo Obinze Ogbonna,5,Left Center Back,4
15,3,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3062,Aaron Cresswell,6,Left Back,5
16,35,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,4273,Reece Oxford,10,Center Defensive Midfield,6
17,8,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3684,Cheikhou Kouyaté,13,Right Center Midfield,7
18,16,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3874,Mark Noble,15,Left Center Midfield,8
19,10,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,27853,Mauro Matías Zárate,17,Right Wing,9
20,27,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3491,Dimitri Payet,21,Left Wing,10
21,15,3754141,bb88fa5c-26c2-47ca-8bde-5de03047a221,3962,Diafra Sakho,23,Center Forward,11
22,33,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3461,Petr Čech,1,Goalkeeper,1
23,2,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,4428,Mathieu Debuchy,2,Right Back,2
24,4,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3475,Per Mertesacker,3,Right Center Back,3
25,6,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3394,Laurent Koscielny,5,Left Center Back,4
26,18,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3498,Ignacio Monreal Eraso,6,Left Back,5
27,16,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3517,Aaron Ramsey,9,Right Defensive Midfield,6
28,19,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,11386,Santiago Cazorla González,11,Left Defensive Midfield,7
29,15,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3525,Alex Oxlade-Chamberlain,17,Right Wing,8
30,11,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3496,Mesut Özil,19,Center Attacking Midfield,9
31,14,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3668,Theo Walcott,21,Left Wing,10
32,12,3754141,84bc92ef-093e-40c3-967d-da4f9aad744a,3604,Olivier Giroud,23,Center Forward,11
33,33,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3461,Petr Čech,1,Goalkeeper,1
34,15,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3525,Alex Oxlade-Chamberlain,2,Right Back,2
35,4,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3475,Per Mertesacker,3,Right Center Back,3
36,6,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3394,Laurent Koscielny,5,Left Center Back,4
37,18,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3498,Ignacio Monreal Eraso,6,Left Back,5
38,16,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3517,Aaron Ramsey,9,Right Defensive Midfield,6
39,19,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,11386,Santiago Cazorla González,11,Left Defensive Midfield,7
40,14,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3668,Theo Walcott,17,Right Wing,8
41,11,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3496,Mesut Özil,19,Center Attacking Midfield,9
42,17,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3385,Alexis Alejandro Sánchez Sánchez,21,Left Wing,10
43,12,3754141,073248dc-dac2-4b95-8389-b67ee8c31c2a,3604,Olivier Giroud,23,Center Forward,11

In [26]:
df1.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'possession',
       'duration', 'match_id', 'type_id', 'type_name', 'possession_team_id',
       'possession_team_name', 'play_pattern_id', 'play_pattern_name',
       'team_id', 'team_name', 'tactics_formation', 'player_id', 'player_name',
       'position_id', 'position_name', 'pass_recipient_id',
       'pass_recipient_name', 'pass_length', 'pass_angle', 'pass_height_id',
       'pass_height_name', 'end_x', 'end_y', 'body_part_id', 'body_part_name',
       'sub_type_id', 'sub_type_name', 'x', 'y', 'under_pressure',
       'outcome_id', 'outcome_name', 'off_camera', 'out', 'counterpress',
       'pass_cross', 'technique_id', 'technique_name', 'aerial_won',
       'foul_committed_card_id', 'foul_committed_card_name',
       'shot_statsbomb_xg', 'goalkeeper_position_id',
       'goalkeeper_position_name', 'pass_assisted_shot_id', 'pass_shot_assist',
       'end_z', 'shot_key_pass_id', 'foul_won_defensive', 'pass_switch',
       'shot_first_time', 'ball_recovery_recovery_failure', 'dribble_overrun',
       'pass_goal_assist', 'pass_cut_back', 'foul_committed_advantage',
       'foul_won_advantage', 'ball_recovery_offensive', 'shot_deflected',
       'block_deflection', 'substitution_replacement_id',
       'substitution_replacement_name', 'shot_one_on_one'],
      dtype='object')

In [28]:
df1.type_name.value_counts()

type_name
Pass               986
Ball Receipt       952
Carry              806
Pressure           244
Ball Recovery      121
Duel                81
Clearance           57
Dribble             47
Block               42
Dribbled Past       37
Goal Keeper         33
Shot                31
Miscontrol          28
Foul Committed      23
Foul Won            23
Dispossessed        20
Interception         9
Substitution         5
Half End             4
Half Start           4
Injury Stoppage      4
Starting XI          2
Tactical Shift       2
Shield               1
Player Off           1
Player On            1
Name: count, dtype: int64