In [1]:

### Punto 1: Análisis de datos

## Obtener información del partido 
# Obtener la información de un partido del Mundial 2022 usando la API de StatsBomb.
#  Podés usar la manera directa de la documentación o el parser de mplsoccer.

## Analizar los datos del partido
# Partido: Argentina vs Arabia Saudita (22 de noviembre de 2022)
# Analizar los eventos del partido, como goles, tiros, pases, etc.
# Identificar los jugadores clave y sus contribuciones al partido.



#IMPORTACION DE LIBRERIAS

from statsbombpy import sb

In [2]:
## BUSCO LA COMPETICION DEL MUNDIAL 2022

sb.competitions()

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,281,Germany,1. Bundesliga,male,False,False,2023/2024,2024-09-28T20:46:38.893391,2025-07-06T04:26:07.636270,2025-07-06T04:26:07.636270,2024-09-28T20:46:38.893391
1,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2024-05-19T11:11:14.192381,NaN,NaN,2024-05-19T11:11:14.192381
2,1267,107,Africa,African Cup of Nations,male,False,True,2023,2024-09-28T01:57:35.846538,NaN,NaN,2024-09-28T01:57:35.846538
3,16,4,Europe,Champions League,male,False,False,2018/2019,2025-05-08T15:10:50.835274,2021-06-13T16:17:31.694,NaN,2025-05-08T15:10:50.835274
4,16,1,Europe,Champions League,male,False,False,2017/2018,2024-02-13T02:35:28.134882,2021-06-13T16:17:31.694,NaN,2024-02-13T02:35:28.134882
...,...,...,...,...,...,...,...,...,...,...,...,...
70,35,75,Europe,UEFA Europa League,male,False,False,1988/1989,2024-02-12T14:45:05.702250,2021-06-13T16:17:31.694,NaN,2024-02-12T14:45:05.702250
71,53,315,Europe,UEFA Women's Euro,female,False,True,2025,2025-07-28T14:19:20.467348,2025-07-29T16:03:07.355174,2025-07-29T16:03:07.355174,2025-07-28T14:19:20.467348
72,53,106,Europe,UEFA Women's Euro,female,False,True,2022,2024-02-13T13:27:17.178263,2024-02-13T13:30:52.820588,2024-02-13T13:30:52.820588,2024-02-13T13:27:17.178263
73,72,107,International,Women's World Cup,female,False,True,2023,2025-07-14T10:07:06.620906,2025-07-14T10:10:27.224586,2025-07-14T10:10:27.224586,2025-07-14T10:07:06.620906
74,72,30,International,Women's World Cup,female,False,True,2019,2024-08-08T15:57:56.748740,2021-06-13T16:17:31.694,NaN,2024-08-08T15:57:56.748740

In [ ]:
## Encuentro en la tabla anteorior que el mundial 2022 masculino:
 # competition_id: 43
 # Season_id: 106 


## Ahhora busco los partidos para enconctrar el partido de Argentina vs Arabia Saudita que es el que quiero analizar.

sb.matches(competition_id=43, season_id=106)

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3857256,2022-12-02,21:00:00.000,International - FIFA World Cup,2022,Serbia,Switzerland,2,3,available,...,2023-04-26T23:49:58.956186,3,Group Stage,Stadium 974,Fernando Andrés Rapallini,Dragan Stojković,Murat Yakin,1.1.0,2,2
1,3869151,2022-12-03,21:00:00.000,International - FIFA World Cup,2022,Argentina,Australia,2,1,available,...,2023-07-30T07:48:51.865595,4,Round of 16,Ahmad bin Ali Stadium,Szymon Marciniak,Lionel Sebastián Scaloni,Graham James Arnold,1.1.0,2,2
2,3857257,2022-11-30,17:00:00.000,International - FIFA World Cup,2022,Australia,Denmark,1,0,available,...,2023-06-20T11:04:37.638969,3,Group Stage,Al Janoub Stadium,Mustapha Ghorbal,Graham James Arnold,Kasper Hjulmand,1.1.0,2,2
3,3857258,2022-11-24,21:00:00.000,International - FIFA World Cup,2022,Brazil,Serbia,2,0,available,...,2023-07-11T14:56:31.096588,1,Group Stage,Lusail Stadium,Alireza Faghani,Telê Santana da Silva,Dragan Stojković,1.1.0,2,2
4,3857288,2022-11-26,12:00:00.000,International - FIFA World Cup,2022,Tunisia,Australia,0,1,available,...,2023-04-27T00:30:07.835815,2,Group Stage,Al Janoub Stadium,Daniel Siebert,Jalel Kadri,Graham James Arnold,1.1.0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,3857265,2022-11-22,18:00:00.000,International - FIFA World Cup,2022,Mexico,Poland,0,0,available,...,2023-04-27T00:49:30.005344,1,Group Stage,Stadium 974,Chris Beath,Gerardo Daniel Martino,Czesław Michniewicz,1.1.0,2,2
60,3857262,2022-12-02,17:00:00.000,International - FIFA World Cup,2022,South Korea,Portugal,2,1,available,...,2023-04-26T23:48:08.999798,3,Group Stage,Education City Stadium,Facundo Tello Figueroa,Paulo Jorge Gomes Bento,Fernando Manuel Fernandes da Costa Santos,1.1.0,2,2
61,3857261,2022-11-29,21:00:00.000,International - FIFA World Cup,2022,Wales,England,0,3,available,...,2023-04-27T00:02:44.241621,3,Group Stage,Ahmad bin Ali Stadium,Slavko Vinčić,Robert Page,Gareth Southgate,1.1.0,2,2
62,3857255,2022-12-01,21:00:00.000,International - FIFA World Cup,2022,Japan,Spain,2,1,available,...,2023-04-26T23:51:48.352990,3,Group Stage,Sheikh Khalifa International Stadium,Victor Miguel de Freitas Gomes,Hajime Moriyasu,Luis Enrique Martínez García,1.1.0,2,2
63,3857254,2022-11-22,15:00:00.000,International - FIFA World Cup,2022,Denmark,Tunisia,0,0,available,...,2023-07-29T19:44:56.738444,1,Group Stage,Education City Stadium,César Arturo Ramos Palazuelos,Kasper Hjulmand,Jalel Kadri,1.1.0,2,2

In [ ]:
## encuentro que el partido corresponde al match_id: 3857300

## busco los eventos del partido usando el match_id

sb.events(match_id=3857300)

d:\PROYECTOS_venv\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,50_50,bad_behaviour_card,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,block_offensive,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Argentina,779,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4141, 'lineup': [{'player': {'id...",Saudi Arabia,799,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Argentina,779,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:00:00.000,Half Start,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3324,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Argentina,779,00:15:01.907,Shield,NaN
3325,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:29:09.256,Bad Behaviour,NaN
3326,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:33:38.484,Bad Behaviour,NaN
3327,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:42:42.675,Bad Behaviour,NaN
3328,NaN,Yellow Card,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Saudi Arabia,799,00:46:02.652,Bad Behaviour,NaN

In [5]:
## Ahora busco traer limipios los eventos del partido usando el parser de mplsoccer

from mplsoccer import Sbopen

parser = Sbopen()

In [11]:
## Averiguo cuantas tuplas hay

len(parser.event(3857300))

4

In [12]:
## defino los dataframes con los eventos del partido 

df1, df2, df3, df4 = parser.event(3857300)

In [14]:
## evaluo cada dataframe para ver que información contiene cada uno

sb.events(match_id=3857300, split=True, flatten_attrs=False).keys()

dict_keys(['starting_xis', 'half_starts', 'passes', 'ball_receipts', 'carrys', 'ball_recoverys', 'pressures', 'miscontrols', 'clearances', 'blocks', 'shots', 'goal_keepers', 'dispossesseds', 'duels', 'dribbles', '50/50s', 'foul_committeds', 'foul_wons', 'interceptions', 'dribbled_pasts', 'injury_stoppages', 'player_offs', 'player_ons', 'substitutions', 'tactical_shifts', 'referee_ball_drops', 'half_ends', 'errors', 'shields', 'bad_behaviours'])

In [31]:
## evaluo cada dataframe para ver que información contiene cada uno


df1

,id,index,period,timestamp,minute,second,possession,duration,match_id,type_id,...,injury_stoppage_in_chain,substitution_replacement_id,substitution_replacement_name,pass_goal_assist,block_offensive,shot_one_on_one,foul_committed_card_id,foul_committed_card_name,bad_behaviour_card_id,bad_behaviour_card_name
0,f4164787-9145-45b3-b56f-c5db10d133ba,1,1,00:00:00,0,0,1,0.000000,3857300,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1932fdd1-e5b1-45bb-9137-63de41cc7e3f,2,1,00:00:00,0,0,1,0.000000,3857300,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,251e8f6b-559a-4c4b-9aaa-33121a64b5fd,3,1,00:00:00,0,0,1,0.000000,3857300,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8539a309-e10f-485d-90b9-b4ce84c9b08c,4,1,00:00:00,0,0,1,0.000000,3857300,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,e785db09-b43e-4806-b292-f2cfcbea20b5,5,1,00:00:00.411000,0,0,2,1.141005,3857300,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3324,57eb2c3b-07f7-46ec-8c45-2fb52ce7d35d,3325,2,00:58:47.631000,103,47,169,NaN,3857300,42,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3325,69024816-4cbd-4995-b34c-a4c6855e0b39,3326,2,00:58:47.631000,103,47,169,1.617700,3857300,43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3326,01b8515f-09b1-4bf6-ae9e-953fbd6bbd79,3327,2,00:58:49.249000,103,49,169,0.653807,3857300,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3327,c35a6d44-adb8-4152-b4e2-cb2650be200a,3328,2,00:58:50.121000,103,50,169,0.000000,3857300,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3328,a97fcaff-5ccd-45a3-a823-b8965f6e7246,3329,2,00:58:50.121000,103,50,169,0.000000,3857300,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
## veo las columnas del dataframe para entender que información contiene cada una


df4.columns

Index(['jersey_number', 'match_id', 'id', 'player_id', 'player_name',
       'position_id', 'position_name', 'event_tactics_id'],
      dtype='str')

In [25]:

# Analizar los eventos del partido, como goles, tiros, pases, etc.
# Identificar los jugadores clave y sus contribuciones al partido.


# de acerdo a lo que estoy buscando busco los campos que me interesan y que cantidad de valores tienen (para saber si me va a servir o no para el análisis )    

df2.type_name.value_counts()

type_name
Pass              1867
Carry             1737
Ball Receipt      1573
Pressure           404
Ball Recovery      112
Dribble             68
Duel                67
Foul Won            53
Clearance           46
Dispossessed        43
Interception        38
Foul Committed      36
Shot                32
Dribbled Past       32
Miscontrol          32
Block               28
Goal Keeper         26
50/50               22
Half Start           4
Half End             4
Player Off           2
Player On            2
Name: count, dtype: int64

In [ ]:
## Me quedo con los eventos de tipo
#  "Pass" : pases realizados
#  "Shot" : tiros realizados
#  "Goal" : goles marcados
#  "Ball Receipt" : recepción de balón
#  "ball recovery" : recuperación de balón
#  "carry" : conducción del balón
#  
# para analizar los pases, tiros y goles del partido.


#"outcome_name" es el campo que debo buscar para saber si el pase, tiro o gol fue exitoso o no.

sb.events(match_id=3857300, split=True, flatten_attrs=False)['shots']

,id,index,period,timestamp,minute,second,type,possession,possession_team,play_pattern,...,position,location,duration,related_events,shot,match_id,possession_team_id,team_id,player_id,under_pressure
0,a8493eb5-a6af-43e6-9457-b77b6e3ab82f,95,1,00:01:34.952,1,34,Shot,3,Argentina,Regular Play,...,Right Center Forward,"[104.5, 44.5]",0.619649,[8eb1c259-fa49-49d2-a65e-3ebef6d53953],"{'statsbomb_xg': 0.15308252, 'end_location': [...",3857300,779,779,5503,NaN
1,55236c4a-e3f0-4c56-ba72-e9c1ac227df2,212,1,00:09:15.590,9,15,Shot,10,Argentina,Other,...,Right Center Forward,"[108.0, 40.0]",0.567491,[99606a9c-391b-4ba0-a099-edddcc5fa405],"{'statsbomb_xg': 0.7835, 'end_location': [120....",3857300,779,779,5503,NaN
2,3cf170da-b2ce-4cac-84e0-b7bc2ffb238f,631,1,00:20:00.702,20,0,Shot,29,Argentina,From Throw In,...,Left Midfield,"[98.4, 20.2]",0.948489,[ada66d58-7d35-4b5b-a81d-d1f30b8547f1],"{'statsbomb_xg': 0.011924569, 'end_location': ...",3857300,779,779,7006,NaN
3,183273de-a7b0-404c-a671-175034820b4d,1265,1,00:41:54.016,41,54,Shot,61,Argentina,From Free Kick,...,Left Center Forward,"[113.2, 33.8]",0.169894,"[2b2f397c-76ca-44be-8c0b-9456cf230fc9, dc47a0a...","{'statsbomb_xg': 0.0877444, 'end_location': [1...",3857300,779,779,11456,NaN
4,3d10b199-c0e5-431b-a44e-1a1a258250aa,1269,1,00:41:56.324,41,56,Shot,61,Argentina,From Free Kick,...,Right Defensive Midfield,"[101.1, 41.8]",0.751256,[ef25c61e-f379-435b-a132-81d647375e35],"{'statsbomb_xg': 0.050540753, 'end_location': ...",3857300,779,779,7797,NaN
5,3d0bfe31-7f21-4257-9b23-c5533d190898,1803,2,00:02:40.060,47,40,Shot,78,Saudi Arabia,From Free Kick,...,Center Forward,"[108.0, 29.6]",1.125889,[b769a5ed-48f6-46e1-adb5-73611c7d44e2],"{'statsbomb_xg': 0.080592275, 'end_location': ...",3857300,799,799,51469,NaN
6,cb3d6d66-9f37-4a42-bcb8-e7f3d4a882a9,1945,2,00:07:36.104,52,36,Shot,88,Saudi Arabia,Regular Play,...,Center Attacking Midfield,"[104.9, 54.1]",0.429016,"[bbc9af57-b73f-43e8-8e5a-d33fcf2ace3f, daba3cf...","{'statsbomb_xg': 0.040064447, 'end_location': ...",3857300,799,799,54144,NaN
7,ee9900a5-1345-47ab-89d5-115349107678,1958,2,00:07:44.366,52,44,Shot,88,Saudi Arabia,Regular Play,...,Left Midfield,"[102.4, 25.3]",0.789755,[e6b7378d-cdda-4062-b57a-7879c2e540b7],"{'statsbomb_xg': 0.03280492, 'end_location': [...",3857300,799,799,5187,NaN
8,b7605623-fd95-4d3a-b758-544ee52f0e40,2286,2,00:17:47.471,62,47,Shot,105,Argentina,From Corner,...,Left Center Back,"[111.1, 39.9]",0.306362,"[53591634-4285-48a7-b09d-72803be9b1af, f90d163...","{'statsbomb_xg': 0.33156127, 'end_location': [...",3857300,779,779,27768,NaN
9,a7844b07-9979-4d38-bb54-631efebd86e7,2290,2,00:17:47.889,62,47,Shot,105,Argentina,From Corner,...,Left Back,"[116.1, 37.2]",0.448108,[ec59e1b8-fbe4-4ff8-a43e-0c80dc93eaaa],"{'one_on_one': True, 'statsbomb_xg': 0.6361934...",3857300,779,779,5507,NaN
10,c5ebefcc-f4ad-4eda-9bc8-5fa0c7154709,2505,2,00:23:35.664,68,35,Shot,112,Argentina,From Corner,...,Left Center Forward,"[116.5, 31.1]",0.390929,"[298ed31f-1114-4285-9f80-94ad6da615b0, 850cccf...","{'statsbomb_xg': 0.077176735, 'end_location': ...",3857300,779,779,11456,True
11,b956a3f0-fcfb-4e2f-b192-f265a11bfc55,2569,2,00:26:54.592,71,54,Shot,116,Argentina,From Throw In,...,Right Midfield,"[111.4, 54.4]",0.569161,[119c9499-1410-4b88-b360-9c1835a6386f],"{'one_on_one': True, 'statsbomb_xg': 0.0639515...",3857300,779,779,2995,NaN
12,e4388b39-5a30-40e2-be15-b281570a6576,2630,2,00:28:37.994,73,37,Shot,118,Argentina,From Throw In,...,Right Midfield,"[86.7, 57.3]",0.777095,"[9543049a-cfd3-47c4-9146-7d418ec18334, edbebd6...","{'statsbomb_xg': 0.015201165, 'end_location': ...",3857300,779,779,2995,NaN
13,baf9173f-0828-443b-a142-61e76c7e0e6b,2674,2,00:30:19.246,75,19,Shot,122,Argentina,From Corner,...,Left Defensive Midfield,"[108.2, 39.6]",0.886367,[3a82d3d5-7f8a-4fb5-8236-d1b3e3019356],"{'statsbomb_xg': 0.036932193, 'end_location': ...",3857300,779,779,38718,NaN
14,cca05e97-8c26-4e29-8f91-642cf41b9858,2725,2,00:34:58.750,79,58,Shot,127,Argentina,From Free Kick,...,Right Center Forward,"[92.8, 47.1]",1.156514,[0c2c334d-484f-412a-9aac-2acaa769fc8a],"{'statsbomb_xg': 0.056788407, 'end_location': ...",3857300,779,779,5503,NaN
15,1fcac061-d04e-4bf2-90cf-88f00958abfc,2843,2,00:38:31.594,83,31,Shot,133,Argentina,Regular Play,...,Right Center Forward,"[113.6, 32.2]",0.562926,[b126fb79-c458-4923-a755-70220ce91db6],"{'statsbomb_xg': 0.077553175, 'end_location': ...",3857300,779,779,5503,NaN
16,7c9a88b1-328a-4075-a662-df7aa6c249f3,3023,2,00:45:34.809,90,34,Shot,144,Argentina,From Corner,...,Right Center Back,"[109.5, 37.8]",0.424789,"[12eed105-5142-4c93-be69-89b601e5ba08, 1df4ce4...","{'statsbomb_xg': 0.048093256, 'end_location': ...",3857300,779,779,3090,True
17,7a79ac21-a20b-4071-a1a8-4a7012cf8c43,3198,2,00:55:03.562,100,3,Shot,153,Argentina,From Corner,...,Left Midfield,"[112.5, 33.2]",0.932726,"[54ad4aec-f3d9-4fa5-9696-5e8d9e6226d4, 9e11663...","{'statsbomb_xg': 0.061390053, 'end_location': ...",3857300,779,779,29560,True